services:
  db:
    image: postgres:15-alpine
    container_name: my-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hieu1205  # Mật khẩu
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Dòng dưới này tự động nạp file schema.sql để khởi tạo table
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  pgdata: